// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: micoserver.proto

package go_micro_service_micoserver

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Micoserver service

func NewMicoserverEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Micoserver service

type MicoserverService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Micoserver_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Micoserver_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Micoserver_BidiStreamService, error)
}

type micoserverService struct {
	c    client.Client
	name string
}

func NewMicoserverService(name string, c client.Client) MicoserverService {
	return &micoserverService{
		c:    c,
		name: name,
	}
}

func (c *micoserverService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Micoserver.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *micoserverService) ClientStream(ctx context.Context, opts ...client.CallOption) (Micoserver_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Micoserver.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &micoserverServiceClientStream{stream}, nil
}

type Micoserver_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type micoserverServiceClientStream struct {
	stream client.Stream
}

func (x *micoserverServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *micoserverServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *micoserverServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *micoserverServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *micoserverServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *micoserverServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *micoserverService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Micoserver_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Micoserver.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &micoserverServiceServerStream{stream}, nil
}

type Micoserver_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type micoserverServiceServerStream struct {
	stream client.Stream
}

func (x *micoserverServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *micoserverServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *micoserverServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *micoserverServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *micoserverServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *micoserverServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *micoserverService) BidiStream(ctx context.Context, opts ...client.CallOption) (Micoserver_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Micoserver.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &micoserverServiceBidiStream{stream}, nil
}

type Micoserver_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type micoserverServiceBidiStream struct {
	stream client.Stream
}

func (x *micoserverServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *micoserverServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *micoserverServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *micoserverServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *micoserverServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *micoserverServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *micoserverServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Micoserver service

type MicoserverHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Micoserver_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Micoserver_ServerStreamStream) error
	BidiStream(context.Context, Micoserver_BidiStreamStream) error
}

func RegisterMicoserverHandler(s server.Server, hdlr MicoserverHandler, opts ...server.HandlerOption) error {
	type micoserver interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Micoserver struct {
		micoserver
	}
	h := &micoserverHandler{hdlr}
	return s.Handle(s.NewHandler(&Micoserver{h}, opts...))
}

type micoserverHandler struct {
	MicoserverHandler
}

func (h *micoserverHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.MicoserverHandler.Call(ctx, in, out)
}

func (h *micoserverHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.MicoserverHandler.ClientStream(ctx, &micoserverClientStreamStream{stream})
}

type Micoserver_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type micoserverClientStreamStream struct {
	stream server.Stream
}

func (x *micoserverClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *micoserverClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *micoserverClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *micoserverClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *micoserverClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *micoserverHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MicoserverHandler.ServerStream(ctx, m, &micoserverServerStreamStream{stream})
}

type Micoserver_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type micoserverServerStreamStream struct {
	stream server.Stream
}

func (x *micoserverServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *micoserverServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *micoserverServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *micoserverServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *micoserverServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *micoserverHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.MicoserverHandler.BidiStream(ctx, &micoserverBidiStreamStream{stream})
}

type Micoserver_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type micoserverBidiStreamStream struct {
	stream server.Stream
}

func (x *micoserverBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *micoserverBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *micoserverBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *micoserverBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *micoserverBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *micoserverBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
